Repository pytroll/pytroll-collectors, pull requests merged in 2023-03, with the labels that each got.

#132 Fix group_by_minutes to include composed filenames
  pytroll_collectors/segments.py
  pytroll_collectors/tests/test_segments.py
Labels: bug

#131 Bugfix segment gathering when segment name has a dash in it
  pytroll_collectors/segments.py
  pytroll_collectors/tests/data/segments_nwcsaf_geo.ini
  pytroll_collectors/tests/test_segments.py
Labels: bug, enhancement

#114 Add an s3stalker daemon
  .github/workflows/ci.yaml
  bin/s3stalker.py
  bin/s3stalker_daemon.py
  continuous_integration/environment.yaml
  doc/source/index.rst
  examples/geographic_gatherer_config.ini_template
  examples/s3stalker_log.yaml_template
  examples/s3stalker_runner.yaml_template
  pytroll_collectors/s3stalker.py
  pytroll_collectors/s3stalker_daemon_runner.py
  pytroll_collectors/scisys.py
  pytroll_collectors/tests/test_fsspec_to_message.py
  pytroll_collectors/tests/test_s3stalker.py
  pytroll_collectors/tests/test_s3stalker_daemon_runner.py
  setup.py
Labels: enhancement, help wanted

#133 Make it possible to tell segment gatherer that all the files are local
  doc/source/index.rst
  examples/segment_gatherer.ini_template
  pytroll_collectors/segments.py
  pytroll_collectors/tests/test_segments.py
Labels: bug, enhancement
